### ISSUE TITLE
setThrottleDuration is not become effective

### ISSUE THREAD

**Issue by lblblb7777** [rosskevin/ifvisible#17]
![image](https://github.com/rosskevin/ifvisible/assets/20125865/8e444f8c-4eb0-4e7f-a3d8-cc4f3592c1bf)
This function is not executed

**Comment by rosskevin** [comment]
Sorry, I didn't see this.  Please submit a PR, thank you!

**Comment by rosskevin** [comment]
:rocket: Issue was released in [`v3.3.4`](https://github.com/rosskevin/ifvisible/releases/tag/v3.3.4) :rocket:
